# SPDX-FileCopyrightText: 2026 Dong Lab, Yale School of Medicine <https://donglab.org>
#
# SPDX-License-Identifier: CC0-1.0

# docker compose -f docker-compose.yml -f docker-compose.build.yml up --build

services:
  atlas:
    build: .
